title: The Elegant Network
author: Elegant Network
email: thenetworkelegant@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: The Elegant Network
  tagline: Perspectives on Networking Infrastructure Design and Practice
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  disqus_shortname: https-elegantnetwork-github-io

  # generate social links in footer
  social_links:
    twitter: ddcumulus
    github:  elegantnetwork
    linkedIn: in/ddutt
    rss: 
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - pages/about.html

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
